### ISSUE TITLE
Flutter SDK article

### ISSUE THREAD

**Issue by just1and0** [OrthoHQ/flutter-ortho#14]

**Comment by just1and0** [comment]
https://blog.okra.ng/okra-react-native-sdk/

**Comment by aniekan12** [comment]
https://medium.com/@ani_88195/how-to-integrate-ortho-in-your-flutter-app-14eebf3f3108

@just1and0

**Comment by just1and0** [comment]
really looks good! let's submit this to the organisation account and I'll take It up from there.
